site_name: Vithai Charitable Trust
# Theme
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  # icon:
  #   logo: material/library
  # features:
  #   # - navigation.tabs
  #   - navigation.instant
  #   - navigation.expand
  palette:
    scheme: default
    primary: teal
    accent: orange

nav:
  - Home: index.md
  - Activities: 
    - Tuition Fee : activities/tuition-fee.md
    - Notebooks : activities/notebooks.md
    - Plantation: activities/plantation.md
  - Gallery: gallery.md

extra_css:
    - css/table.css